version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
  - package-ecosystem: 'docker'
    directory: '/docker/build'
    schedule:
      interval: 'weekly'
