services:
  node:
    container_name: e-xode-vue-ssr
    build:
      context: 'docker/dev/node'
    volumes:
      - '.:/app'
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    env_file:
      - ./.env
    environment:
      - NODE_OPTIONS=--unhandled-rejections=warn
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    shm_size: '2gb'
    tty: false
    stdin_open: false
    networks:
      - e-xode
networks:
  e-xode:
    driver: bridge
    external: true
