version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.0
  node: circleci/node@5.1.0

jobs:
  unitesting:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: run front-end lint
          command: npm run lint
      - run:
          name: run front-end unit tests
          command: npm run test:unit:coverage
      - coveralls/upload:
          flag_name: unitesting
          verbose: true

  done:
    executor: node/default

    steps:
    - coveralls/upload:
        carryforward: "unitesting"

workflows:
  unit-testing:
    jobs:
      - unitesting
