name: 'npm-test'

on:
  push:
    branches: ['master', 'development']
  pull_request:
    branches: ['master', 'development']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm ci
      - run: npm run lint:check
      - run: npm run test:run
